Month12/step1
SergeyKukhtalevV/algososh pull request #1
Opened 2023-05-19 15:49 UTC by SergeyKukhtalevV

Добрый день!

Прошу проверить!

2023-05-19 16:43 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Отлично типизировали проект
- Хорошо сделаны классы
- Хорошо сделали визуализацию

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- При запуске "Сортировки массива" необходимо чтобы автоматически был создан случайный массив
- В "Сортировке массива" пузыркём не работает сортировка по убыванию, вместо неё запускается режим по возрастанию.
- В `Очереди` если заполнить все элементы, а потом очистить кнопкой, то невозможно ничего больше добавить. 
- Файл app.test.js нужно удалить, так как он не относится к проекту
- app.css нужно сделать модулем app.module.css, а в компоненте использовать модульные классы, а не строки

- При невалидном индексе кнопки активны. Нужно определять максимально возможный индекс по длине массива минус 1

<img width="783" alt="Снимок экрана 2023-05-19 в 19 37 02" src="https://github.com/SergeyKukhtalevV/algososh/assets/60173362/8dd378f3-9e66-4355-84af-e8e161892b74">

- В Связанном Списке **При удалении элемента по индексу** сначала необходимо выделять цветом элементы, пока не достигнем нужного индекса. Затем очистить значение в элементе и снизу отобразить маленький кружок с удаляемым значением. Так же при удалении кружочек появляющийся внизу пустой, а должен быть с цифрой.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-20 08:02 UTC, SergeyKukhtalevV commented
Поправил замечания.
Прошу проверить

2023-05-20 15:54 UTC, andryxxa93 commented
Всё супер, только один момент не исправили - 
- При невалидном индексе кнопки активны. Нужно определять максимально возможный индекс по длине массива минус 1

<img width="732" alt="Снимок экрана 2023-05-20 в 18 54 25" src="https://github.com/SergeyKukhtalevV/algososh/assets/60173362/5e0d62d7-fc23-4ea6-bd32-0f9a254a1d74">

2023-05-20 16:11 UTC, SergeyKukhtalevV commented
Да, извините, пропустил это замечание. Сейчас пофиксил

2023-05-21 09:21 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-22 07:34 UTC, merged